[target.thumbv7em-none-eabihf]
rustflags = ["-C", "link-arg=-Tneotron-cortex-m.ld"]

[target.thumbv7em-none-eabi]
rustflags = ["-C", "link-arg=-Tneotron-cortex-m.ld"]

[target.thumbv7m-none-eabi]
rustflags = ["-C", "link-arg=-Tneotron-cortex-m.ld"]

[target.thumbv6m-none-eabi]
rustflags = ["-C", "link-arg=-Tneotron-cortex-m.ld"]
