[target.thumbv7em-none-eabihf]
rustflags = [
    "-Clink-arg=-Tneotron-cortex-m.ld", 
    "-Clink-arg=--nmagic"
]

[target.thumbv7em-none-eabi]
rustflags = [
    "-Clink-arg=-Tneotron-cortex-m.ld", 
    "-Clink-arg=--nmagic"
]

[target.thumbv7m-none-eabi]
rustflags = [
    "-Clink-arg=-Tneotron-cortex-m.ld", 
    "-Clink-arg=--nmagic"
]

[target.thumbv6m-none-eabi]
rustflags = [
    "-Clink-arg=-Tneotron-cortex-m.ld", 
    "-Clink-arg=--nmagic"
]
