[workspace]
members = [
    "fault",
    "hello",
    "hexdump",
    "input-test",
    "panic",
]
resolver = "2"

[workspace.dependencies]
neotron-sdk = { path = "..", version = "0.2" }

[profile.release]
opt-level = "z"
lto = "fat"
