on: [push, pull_request]
name: Build (and Release)

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (and Release)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Add targets
        run: |
          rustup target add thumbv6m-none-eabi

      - name: Build lib (native)
        run: |
          cargo build --verbose

      - name: Test lib (native)
        run: |
          cargo test --verbose

      - name: Build lib (Cortex-M0), OS mode
        run: |
          cargo build --verbose --target=thumbv6m-none-eabi --features=os

      - name: Build samples (Cortex-M0)
        run: |
          cd samples && cargo build --verbose --target=thumbv6m-none-eabi
