on: [push, pull_request]
name: Build (and Release)

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (and Release)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Add targets
        run: |
          rustup target add thumbv6m-none-eabi
          rustup target add thumbv7m-none-eabi
          rustup target add thumbv7em-none-eabi
          rustup component add llvm-tools
          cargo install cargo-binutils

      - name: Add targets
        run: |
          sudo apt-get -y install gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Build lib (native)
        run: |
          cargo build --verbose

      - name: Test lib (native)
        run: |
          cargo test --verbose

      - name: Build samples (Cortex-M0+)
        run: |
          cd samples && ./build.sh thumbv6m-none-eabi

      - name: Build samples (Cortex-M3)
        run: |
          cd samples && ./build.sh thumbv7m-none-eabi

      - name: Build samples (Cortex-M4)
        run: |
          cd samples && ./build.sh thumbv7em-none-eabi
