name: Format

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Rust
        run: rustup component add rustfmt

      - name: Check Format
        run: cargo fmt -- --check

      - name: Check Format
        run: cd samples && cargo fmt -- --check
